### ISSUE TITLE
telnet to gogo shell

### ISSUE THREAD

**Issue by gabbo9lli** [mdelapenya/docker-liferay-portal#10]
Hi Manuel.
I'm not able to connect to gogo shell with this command.

After this command,
docker run -p 8080:8080 -p 11311:11311 mdelapenya/liferay-portal

I obtained

16:20:06,301 INFO  [Start Level: Equinox Container: a006b0ae-32bb-0017-1b7e-c41741c30fee][BundleStartStopLogger:35] STARTED org.apache.felix.gogo.command_0.12.0 [31]
16:20:06,325 INFO  [Start Level: Equinox Container: a006b0ae-32bb-0017-1b7e-c41741c30fee][BundleStartStopLogger:35] STARTED org.apache.felix.gogo.runtime_0.10.0 [32]
16:20:06,366 INFO  [Start Level: Equinox Container: a006b0ae-32bb-0017-1b7e-c41741c30fee][BundleStartStopLogger:35] STARTED org.apache.felix.gogo.shell_0.10.0 [33]

Then, I typed

telnet localhost 11311
Trying ::1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

how can I connect to gogo shell after I turned on container?
Maybe, I have to write some options?

Thanks,
Regards
gabbo

**Comment by gabbo9lli** [comment]
Hi Manuel. 
I solved my issue including in 
$LIFERAY_CONFIG_DIR/portal-ext.properties
a portal-ext.properties enabling this option.

 module.framework.properties.osgi.console=0.0.0.0:11311

thanks.
regards
gabbo

**Comment by mdelapenya** [comment]
Hey @gabbo9lli, I'm on paternity leave, sorry for the late response...

Yes, this is something that can be overridden allowing OSGi to listen at any interface.
