### ISSUE TITLE
How can i get the 7.0 ce GA6 version

### ISSUE THREAD

**Issue by Rostry** [mdelapenya/docker-liferay-portal#20]
Hi Manuel nice to meet you, i have a doubt isn´t an issue. 

Well can you please help me, how can i get the https://github.com/mdelapenya/docker-liferay-portal/tree/7-ce-ga6-tomcat-mysql i run the docker pull mdelapenya/liferay-portal but i am not sure how can i get this specific version.

Thanks in advance for your kindly support.

Thanks!

**Comment by mdelapenya** [comment]
Hey @rostry, please go to docker hub, to my account: mdelapenya. There you'll find the Liferay-portal repo with all tags

Thanks

**Comment by Rostry** [comment]
Well @mdelapenya i do that and i get the Liferay-portal repo with all tags is : https://github.com/mdelapenya/docker-liferay-portal/tree/7-ce-ga6-tomcat-mysql 

right? 

But my question is how can i get this version.

Thanks.

**Comment by mdelapenya** [comment]
Hey @Rostry, can I close this ticket?

**Comment by mdelapenya** [comment]
Closing as inactive
