### ISSUE TITLE
How about liferay docker cluster with one remote database?

### ISSUE THREAD

**Issue by zhonghuasheng** [mdelapenya/docker-liferay-portal#4]
Does it possible to use liferay docker cluster with one database? I know we can setup liferay cluster and configure the db connection with one database in portal-ext.properties, but I wonder does it suitable for docker with liferay boundle?

**Comment by mdelapenya** [comment]
Hey @zhonghuasheng, it's up to you in the sense that Docker is not a restriction in terms of the stack. I mean, would you set up a liferay cluster with one db using VirtualBox or physical machines?

Docker has its own characteristics, but in the end it's a virtualisation technology, so you should be able to configure same stack using Docker or VirtualBox.

wdyt?

**Comment by zhonghuasheng** [comment]
Yes, I will have a try and give you a feedback. Thank you very much.
