### ISSUE TITLE
Document or replace ONBUILD instructions

### ISSUE THREAD

**Issue by mdelapenya** [mdelapenya/docker-liferay-portal#5]
Could you please take a look @sammonsjl?

When using this image as base, it forces to have `configs` and `deploy` folders with any element inside, which could not be present. If we cannot replace that, then we must document that behaviour.

**Comment by sammonsjl** [comment]
Hi @mdelapenya, I decided the best thing to do was remove ONBUILD and just include COPY instructions in the child Dockerfiles.  I sent you a series of pull requests to make the change and also fixed the mysql container so that it would work with utf8 again.

**Comment by mdelapenya** [comment]
Merged, thanks!

![image](https://media.giphy.com/media/D0WOL0ogZIoG4/giphy.gif)
